from selenium import webdriver
from time import sleep
from selenium.webdriver.common.keys import Keys
k=6051071001
for k in range(6051071001,6051071146):
    f = open('student.txt',"a",encoding='utf-8')
    browser = webdriver.Chrome(executable_path = "./chromedriver.exe")
    browser.get("http://smart.utc2.edu.vn:8383/HTDRL/login.jsp")
    assert "Python" in driver.title
    sleep(4)
    user = browser.find_element_by_name("j_username")
    user.send_keys("6051071055")
    passs = browser.find_element_by_name("j_password")
    passs.send_keys("06/04/2001")
    passs.send_keys(Keys.ENTER)
    tim = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/div/div[1]/div[3]")
    tim.click()
    sleep(2)
    dien = browser.find_element_by_class_name("z-textbox")
    dien.send_keys(str(k))
    enter = browser.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div/button")
    enter.click()
    sleep(1)
    f.write('{')
    mssv = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[5]/td[2]/div/input")
    f.write('"tên khóa học":'+mssv.get_attribute('value')+',')
    ten = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[1]/td[2]/div/input")
    f.write('"Họ và tên":'+ten.get_attribute('value')+',')
    born = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[2]/td[2]/div/i/input")
    f.write('"Ngày sinh":'+born.get_attribute('value')+',')
    grade = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[1]/div/div/table/tbody/tr[4]/td[2]/div/i/input")
    f.write('"Lớp":'+grade.get_attribute('value')+',')
    email = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[3]/div/div/table/tbody/tr[1]/td[2]/div/input")
    f.write('"Email":'+email.get_attribute('value')+',')
    phone = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[3]/div/div/table/tbody/tr[2]/td[2]/div/input")
    f.write('"Điện thoại":'+phone.get_attribute('value')+',')
    address = browser.find_element_by_xpath("/html/body/table/tbody/tr[1]/td[2]/table/tbody/tr/td[2]/div/div[3]/div/div/div/table/tbody/tr/td/table/tbody/tr/td[3]/div/div/table/tbody/tr[4]/td[2]/div/input")
    f.write('"Địa chỉ":'+address.get_attribute('value'))
    f.write('},')
    # browser.close()
